language: php

# faster builds on docker-container setup
sudo: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

matrix:
    fast_finish: true
    exclude:
        - php: hhvm
          env: DB=pgsql  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
    allow_failures:
        - php: 7.0
        - php: hhvm

branches:
    only:
        - v2

install:
    - composer self-update

before_script:
    # disable xdebug since we don't use code-coverage for now
    - phpenv config-rm xdebug.ini
    # build coverage only on one build, to speed up results feedbacks
    # - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; else PHPUNIT_FLAGS=""; fi;
    - if [[ "$DB" = "pgsql" ]]; then psql -c 'create database wallabag;' -U postgres; fi;

script:
    - ant prepare-$DB
    - bin/phpunit --exclude-group command-doctrine -v

# after_script:
    # - |
        # if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
            # wget https://scrutinizer-ci.com/ocular.phar
            # php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        # fi
